### ISSUE TITLE
seemingly no chatGTP option "develop your own plugin" 

### ISSUE THREAD

**Issue by glumac** [sitepoint-editors/chatgpt-plugin-quickstart-js#1]
When attempting step 4:

_Select "Develop your own plugin"_

It appears chatGTP may not current have a "develop your own plugin" option (or the steps to create one have changed).

<img width="802" alt="plugin-store" src="https://github.com/sitepoint-editors/chatgpt-plugin-quickstart-js/assets/4953967/98054955-7951-4d42-b881-0078a1ea6ae3">

Context: ChatGTP plus subscriber

**Comment by jameshibbard** [comment]
Hi,

Plug-in development is still behind a waitlist and you need to be approved.

Did you join the [waitlist](https://openai.com/waitlist/plugins) (linked in the prerequisites section at the top of the article)?

You can find (slightly) more info here:

https://community.openai.com/t/why-isnt-the-develop-your-own-plugin-available/220435

**Comment by glumac** [comment]
Ah, the "If you don’t have access yet through a paid account, you can join the waitlist here" language is what threw me, and I should have read the waitlist page header more carefully to see that even paid accounts currently need to join waitlist. Thank you, cheers!

**Comment by jameshibbard** [comment]
No worries :smile:
